//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoRent.Exceptions
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotoRent.Exceptions.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A motorcycle with this license plate already exists..
        /// </summary>
        public static string ALREADY_EXISTS_LICENSE_PLATE
        {
            get
            {
                return ResourceManager.GetString("ALREADY_EXISTS_LICENSE_PLATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A motorcycle with this VIN already exists..
        /// </summary>
        public static string ALREADY_EXISTS_VIN
        {
            get
            {
                return ResourceManager.GetString("ALREADY_EXISTS_VIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brand must be provided..
        /// </summary>
        public static string EMPTY_BRAND
        {
            get
            {
                return ResourceManager.GetString("EMPTY_BRAND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to License plate must be provided..
        /// </summary>
        public static string EMPTY_LICENSE_PLATE
        {
            get
            {
                return ResourceManager.GetString("EMPTY_LICENSE_PLATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model must be provided..
        /// </summary>
        public static string EMPTY_MODEL
        {
            get
            {
                return ResourceManager.GetString("EMPTY_MODEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VIN must be provided..
        /// </summary>
        public static string EMPTY_VIN
        {
            get
            {
                return ResourceManager.GetString("EMPTY_VIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year must be greater than or equal to zero..
        /// </summary>
        public static string INVALID_YEAR
        {
            get
            {
                return ResourceManager.GetString("INVALID_YEAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        public static string UNKNOWN_ERROR
        {
            get
            {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
